import { Timestamp } from "firebase/firestore";

export type BookingStatus = 'pending' | 'confirmed' | 'completed' | 'cancelled';

export type TourCategory = 'camping_hiking' | 'day_tour';

export interface TourPricing {
  perPersonFee: number; // Base per person fee (without meals). If private, fullCab = perPersonFee * 8
  perPersonWithMeals?: number; // Per person fee with meals
  fullTourPrice?: number; // Calculated on creation (perPersonFee * 8)
  fullTourPriceWithMeals?: number; // Calculated on creation (perPersonWithMeals * 8)
}

export interface TourOptionalAddon {
  name: string;
  priceLKR: number;
}

export interface Tour {
  id?: string; // Auto-generated by Firestore or slug
  title: string;
  slug: string;
  tourType: 'private' | 'group';
  scheduledDate?: string; // YYYY-MM-DD or ISO string for Group tours
  category: TourCategory;
  description: string;
  durationHours?: number; // Optional now, since camping uses durationDays
  durationDays?: string; // e.g., "2 DAYS / 1 NIGHT"
  startTime?: string; // e.g., "12:00 PM"
  startingPoint?: string; // e.g., "Belihuloya Rest House" (for Day Tours)
  isActive?: boolean; // Tour status
  totalSeats?: number; // Total capacity for group tours
  bookedSeats?: number; // Currently booked seats for group tours
  imageUrl: string;
  pricing: TourPricing;
  features: string[]; // e.g. ["Private safari cab", "Visit all attractions"]
  providedItems?: string[]; // e.g., ["Camping Tent", "Power Bank"]
  routeProgram?: string[]; // e.g., ["Surathali Ella", "Ohiya Camping"]
  optionalAddons?: TourOptionalAddon[];
  createdAt?: Timestamp | Date;
}

export interface Booking {
  id?: string; // Auto-generated by Firestore
  tourId: string;
  tourName: string;
  tourType: 'private' | 'group';
  includesMeals: boolean;
  pricingBasis: 'full_tour' | 'per_person';
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  date: Timestamp | Date; // The date of the tour
  pax: number; // Number of passengers
  totalPrice: number;
  status: BookingStatus;
  createdAt: Timestamp | Date;
  notes?: string;
}

// Track daily inventory of jeeps
export interface Inventory {
  id: string; // The ID should ideally be the date string e.g. "YYYY-MM-DD"
  date: string; 
  jeepsBooked: number; // Current number of jeeps booked for this day
  maxJeeps: number; // The maximum capacity for this specific day
}

export interface TikTokClip {
  id: string;
  publicId: string;
  url: string;
}

export interface SiteSettings {
  id?: string;
  socialLinks: {
    facebook: string;
    tiktok: string;
    youtube: string;
    instagram: string;
  };
  pixelIds: {
    meta: string;
    tiktok: string;
  };
  tiktokClips: TikTokClip[];
  updatedAt?: Timestamp | Date;
}
