import { Timestamp } from "firebase/firestore";

// The status of a booking in the system
export type BookingStatus = 'pending' | 'confirmed' | 'completed' | 'cancelled';

export interface Booking {
  id?: string; // Auto-generated by Firestore
  tourId: string;
  tourName: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  date: Timestamp | Date; // The date of the tour
  pax: number; // Number of passengers
  totalPrice: number;
  addons: string[];
  status: BookingStatus;
  createdAt: Timestamp | Date;
  notes?: string;
}

// Track daily inventory of jeeps
export interface Inventory {
  id: string; // The ID should ideally be the date string e.g. "YYYY-MM-DD"
  date: string; 
  jeepsBooked: number; // Current number of jeeps booked for this day
  maxJeeps: number; // The maximum capacity for this specific day
}
